### ISSUE TITLE
Styles disappear in embroider production build when there are css layers in app.css

### ISSUE THREAD

**Issue by candunaj** [embroider-build/embroider#1358]
When you specify CSS layers at the top of `app.css` then imports below it disappear in the embroider production build. The development build works as expected (nothing is removed from app.css).

So when you specify the following `app.css` file

```css
/* app.css */
@layer base, components;
@import 'global.css' layer(base);

h1{
  color: red;
}
```

when you run `ember serve --environment=production` then you get the following `app.css` in the `dist/assets` directory:

```css
/* app.css */
@layer base, components;
h1{
  color: red;
}
```
> Import disappeared!

When you move defining layers under the imports then everything works as expected and nothing is removed from `app.css`

[I have put together a repo with the issue here.](https://github.com/candunaj/css-layer-embroider-bug)
