### ISSUE TITLE
The order of CSS included by app.import is different from ember-cli

### ISSUE THREAD

**Issue by astronomersiva** [embroider-build/embroider#337]
Consider a class `dropdown`. In ember-cli, if there was an addon that had styles for this as

```css
.dropdown {
    color: red;
}
```

and if there was an `app.import('vendor/style.css')` that had contents as

```css
.dropdown {
    color: blue;
}
```

the color of the contents of `dropdown` were `blue`. This is because, the `vendor.css` was generated as:

```css
.dropdown {
    color: red;
}
.dropdown {
    color: blue;
}
```

In embroider, this order seems to have changed.
```css
.dropdown {
    color: blue;
}
.dropdown {
    color: red;
}
```
